### ISSUE TITLE
Deprecate this package after unix-2.8.0.0

### ISSUE THREAD

**Issue by hasufell** [wrengr/unix-bytestring#17]
Context:

* https://github.com/haskell/unix/pull/202
* https://hasufell.github.io/posts/2022-06-29-fixing-haskell-filepaths.html
* https://github.com/haskell/unix/blob/43acabe288f58e3d8c9c71e15d4dd7b586e26efb/changelog.md

**Comment by wrengr** [comment]
From what I can see unix-2.8.0.0 only offers the POSIX.1 syscalls (`read`, `write`, `lseek`) and only in their simplest forms (`fdFoo` and `fdFooBuf`). However it does not offer the more sophisticated forms of those syscalls (`tryFdFooBuf` and `fdFoos`). And more importantly, it doesn't provide the XPG4.2 syscalls (`readv`, `pread`, `writev`, `pwrite`)— which were the the specific motivation for creating this package in the first place.

I'll have to release a breaking version change, since unix-2.8.0.0 (actually unix-2.5.1.0 iirc) stole the module name, and add some cpp to reexport the new implementations when available, but that's about it.

Personally I'd love for this package to be incorporated wholesale into the unix package itself. But the times I've tried pursuing that in the past there was always some peculiar antipathy from the unix developers. And this ultimatum of yours indicates that that antipathy is still there.

**Comment by hasufell** [comment]
> And this ultimatum of yours indicates that that antipathy is still there.

You're quite mistaken.

**Comment by faithanalog** [comment]
at any rate, readv/writev/pread/pwrite are incredibly useful syscalls and the main reason i found this package in the first place, so it doesn't really make sense to try to mark this as deprecated when those aren't present in the proposed replacement.
